apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec: # this is the part that differs between different service objects
  type: NodePort # Cluster IP is default type of service if not specified!
  ports: # Look at the included image in the readme to services folder to find what these are actually mapping to :)
    - port: 80 # [Required]
      targetPort: 80 # If this isn't provided, it is assumed to be the same as port
      nodePort: 30008 # If this isn't provided, it is randomly chosen 30000-32767
  selector: # Provide a list of labels to identify the pod to apply the service to
    app: myapp
    type: front-end
